### ISSUE TITLE
Incorrect handling when clocks are moved backward?

### ISSUE THREAD

**Issue by breezewish** [chronotope/chrono-tz#23]
Consider 06 November, 2011 01:59:59 AM in America/Los_Angeles:

```rust
let tz: chrono_tz::Tz = "America/Los_Angeles".parse().unwrap();
let dt = tz.ymd_opt(2011, 11, 6).and_hms_opt(1, 59, 59);
println!("{:?}", dt);
```

According to [time zone information](https://timezonedb.com/time-zones/America/Los_Angeles):

> After Sunday, 06 November, 2011 01:59:59 AM:
> Clocks were moved backward to become Sunday, 06 November, 2011 01:00:00 AM

So `06 November, 2011 01:59:59` is ambiguous, but the output is `None`.

**Comment by breeswish** [comment]
Also, when using local, the problem does not exist:

```rust
    let t = Local.ymd_opt(1988, 09, 10).and_hms_opt(23, 59, 59);
    println!("{}", t.unwrap().timestamp());

    let tz: Tz = "Asia/Shanghai".parse().unwrap();
    let t = tz.ymd_opt(1988, 09, 10).and_hms_opt(23, 59, 59);
    println!("{}", t.unwrap().timestamp());
```

My time zone is Asia/Shanghai and the first one will success and the second one will fail.

**Comment by breeswish** [comment]
A friendly ping

**Comment by kennytm** [comment]
This issue has nothing to do with `chrono-tz`, the implementation properly returns `LocalResult::Ambiguous`. The problem is that `chrono`'s implementation of `LocalResult::and_hms_opt` [*discards* the `Ambiguous` result](https://github.com/chronotope/chrono/blob/1407309b877b201ff79c016d1d1b1c261c02c386/src/offset/mod.rs#L96-L103).

`Local` "works" because `Local` [never returns anything besides `LocalResult::Single`](https://github.com/chronotope/chrono/blob/1407309b877b201ff79c016d1d1b1c261c02c386/src/offset/local.rs#L134), even in case of non-existing time (due to the `tm → time_t → tm` roundtrip):

```rust
use chrono::*;

fn main() {
	let dt1 = chrono_tz::America::Los_Angeles.ymd_opt(2018, 3, 11).and_hms_opt(2, 15, 0);
	let dt2 = Local.ymd_opt(2018, 3, 11).and_hms_opt(2, 15, 0);
	println!("{:?}", dt1);
        // None 👌 
	println!("{:?}", dt2);
        // Single(2018-03-11T03:15:00-07:00) 😕 
}
```

**Comment by sparky8251** [comment]
This seems related to my issue, [chrono #318](https://github.com/chronotope/chrono/issues/318). I found other related issues around this as well.
