### ISSUE TITLE
Is there a way to get system's `Tz`

### ISSUE THREAD

**Issue by nooberfsh** [chronotope/chrono-tz#81]

**Comment by quickdudley** [comment]
I'd be happy to do a PR to add this functionality to chrono-tz; especially since I also need it. However there's no platform-independent way to do this and I won't have access to a Windows environment for a few of days.

On Unix-like the best way is to try each of these and use the first one that gives you a valid timezone identifier

1. Check the `TZ` environment variable
2. If `/etc/localtime` is a symbolic link then check where it points: the path should be of the form `{outer directory}/zoneinfo/{timezone identifier}`
3. Search `/usr/share/zoneinfo` and `/var/db/timezone/zoneinfo` for a file which is the same as `/etc/localtime`

Windows has a C function called `GetTimeZoneInformation` in `timezoneapi.h` which is documented at https://docs.microsoft.com/en-us/windows/win32/api/timezoneapi/nf-timezoneapi-gettimezoneinformation

**Comment by astraw** [comment]
This is the raison d'etre of [`iana-time-zone`](https://crates.io/crates/iana-time-zone). It's output can be parsed to make a `chrono_tz::Tz` like so:

```rust
let tz_str = iana_time_zone::get_timezone()?;
let tz: chrono_tz::Tz = tz_str.parse()?;
```

**Comment by djc** [comment]
I think that's a pretty good way to do it, so I'll close this for now.
